import Taro from '@tarojs/taro';
import dayjs from 'dayjs';
import type { Activity, MonthlyReport } from '@/types/activity';
import type { UsageRecord, Equipment } from '@/types/equipment';
import { mockEquipments } from '@/data/mockEquipments';

export const REPORT_SHOWN_STORAGE_KEY = (month: string) => `report_shown_${month}`;
export const getReportShownMonth = () => Taro.getStorageSync(REPORT_SHOWN_STORAGE_KEY(dayjs().format('YYYY-MM')));
export const setReportShownMonth = () => Taro.setStorageSync(REPORT_SHOWN_STORAGE_KEY(dayjs().format('YYYY-MM')), true);

const getEquipmentName = (equipmentId: string): string => {
  const equipment = mockEquipments.find(e => e.id === equipmentId);
  return equipment?.name || equipmentId;
};

export const generateMonthlyReport = (
  activities: Activity[],
  usageRecords: UsageRecord[],
  month: string = dayjs().format('YYYY-MM')
): MonthlyReport => {
  console.log('[ReportGenerator] 生成月度报告', { month, activityCount: activities.length });

  const monthActivities = activities.filter(a => 
    dayjs(a.startDate).format('YYYY-MM') === month || 
    dayjs(a.endDate).format('YYYY-MM') === month
  );

  const totalParticipants = monthActivities.reduce((sum, a) => sum + a.currentParticipants, 0);
  
  const monthUsage = usageRecords.filter(r => dayjs(r.useDate).format('YYYY-MM') === month);
  const equipmentUsageCount = monthUsage.length;

  const equipmentUsageMap = new Map<string, number>();
  monthUsage.forEach(r => {
    const name = getEquipmentName(r.equipmentId);
    equipmentUsageMap.set(name, (equipmentUsageMap.get(name) || 0) + 1);
  });
  const equipmentUsageFrequency = Array.from(equipmentUsageMap.entries())
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 10);

  const ratingDistribution: Record<number, number> = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
  let totalRating = 0;
  let ratedCount = 0;

  monthActivities.forEach(a => {
    if (a.ratings) {
      ratingDistribution[Math.round(a.ratings.averageRating)] = 
        (ratingDistribution[Math.round(a.ratings.averageRating)] || 0) + 1;
      totalRating += a.ratings.averageRating;
      ratedCount++;
    }
  });

  const campRatingDistribution = Object.entries(ratingDistribution)
    .map(([rating, count]) => ({ rating: parseInt(rating), count }));

  const averageCampRating = ratedCount > 0 ? totalRating / ratedCount : 0;

  const leaderActivityMap = new Map<string, number>();
  monthActivities.forEach(a => {
    leaderActivityMap.set(a.leaderName, (leaderActivityMap.get(a.leaderName) || 0) + 1);
  });
  const newActivitiesByLeader = Array.from(leaderActivityMap.entries())
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);

  const report: MonthlyReport = {
    month,
    totalActivities: monthActivities.length,
    totalParticipants,
    equipmentUsageCount,
    equipmentUsageFrequency,
    campRatingDistribution,
    averageCampRating: Math.round(averageCampRating * 10) / 10,
    newActivitiesByLeader
  };

  console.log('[ReportGenerator] 报告生成完成', report);
  return report;
};

export const exportToPDF = async (report: MonthlyReport): Promise<string | null> => {
  console.log('[ReportGenerator] 开始导出PDF', report);
  
  try {
    const { jsPDF } = await import('jspdf');
    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.setTextColor(46, 125, 50);
    doc.text('户外活动月度报告', 105, 20, { align: 'center' });

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`报告月份: ${report.month}`, 20, 35);

    doc.setFontSize(14);
    doc.setTextColor(46, 125, 50);
    doc.text('一、活动概览', 20, 50);

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(`• 活动总数: ${report.totalActivities} 场`, 25, 60);
    doc.text(`• 参与人数: ${report.totalParticipants} 人`, 25, 70);
    doc.text(`• 装备使用次数: ${report.equipmentUsageCount} 次`, 25, 80);
    doc.text(`• 营地平均评分: ${report.averageCampRating} 分`, 25, 90);

    doc.setFontSize(14);
    doc.setTextColor(46, 125, 50);
    doc.text('二、装备使用频率 Top 5', 20, 110);

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    report.equipmentUsageFrequency.slice(0, 5).forEach((item, index) => {
      doc.text(`${index + 1}. ${item.name}: ${item.count} 次`, 25, 120 + index * 10);
    });

    doc.setFontSize(14);
    doc.setTextColor(46, 125, 50);
    doc.text('三、营地评分分布', 20, 180);

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    report.campRatingDistribution.forEach((item) => {
      doc.text(`${item.rating} 星: ${item.count} 个`, 25, 190 + item.rating * 10);
    });

    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by 露营管家', 105, 280, { align: 'center' });

    const pdfOutput = doc.output('datauristring');
    console.log('[ReportGenerator] PDF生成成功');

    Taro.showModal({
      title: '导出成功',
      content: `${report.month}月度报告已生成PDF文件，可保存到本地或分享给好友`,
      confirmText: '好的',
      showCancel: false
    });

    console.log('[ReportGenerator] PDF Data URI:', pdfOutput.substring(0, 100) + '...');
    return pdfOutput;
  } catch (error) {
    console.error('[ReportGenerator] PDF导出失败', error);
    Taro.showToast({
      title: '导出失败，请重试',
      icon: 'none'
    });
    return null;
  }
};
